New site astro
Groupe-Gaillard/matou-technologies.fr pull request #9
Opened 2024-08-19 12:29 UTC by MarcoPOtard

2024-08-26 10:17 UTC, tpointel requested changes

2024-08-26 10:17 UTC, tpointel commented on src/content/page/index.mdx
> +    **Coucou.**
**Nous sommes les Matous.**

# Agence technologique.

2024-08-26 10:17 UTC, tpointel commented on src/content/page/index.mdx
> +      - title: Développement Web
Développement ~~web~~

2024-08-26 10:17 UTC, tpointel commented on src/content/page/index.mdx
> +        content: Des logiciels sur mesure pour améliorer les process internes, lancer une nouvelle application ou automatiser des tâches.
Des logiciels, sites web, sur mesure ...

2024-08-26 10:17 UTC, tpointel commented on src/content/page/index.mdx
> +          Symfony, React.js
Symfony, React.js, Next.js

2024-08-26 10:17 UTC, tpointel commented on src/content/page/index.mdx
> +      **planet.fr - e-sante.fr - medisite**
**planet.fr - e-sante.fr - medisite.fr**

2024-08-26 10:17 UTC, tpointel commented on src/content/page/index.mdx
> +      thumbnail: /src/assets/clients-matou-2.jpg
Mettre les logos dans l'ordre :
- NPM
- planet.fr
- e-sante.fr
- Medisite

2024-08-26 10:17 UTC, tpointel commented on src/content/page/index.mdx
> +      <span style="color: #F28705">GOOGLEWORKSPACE / GOOGLECLOUD / MICROSOFT AWS / STRIPE DIDOMI XIVO / FREEPRO DELL APPLE
Il manque des /

GOOGLEWORKSPACE / GOOGLECLOUD / MICROSOFT / AWS / STRIPE / DIDOMI / XIVO / FREEPRO / DELL / APPLE / SAMSUNG / TP-LINK / ZEBRA / EPSON / CANON / BROTHERS

2024-08-26 10:17 UTC, tpointel commented on src/content/page/mentions-legales.mdx
> +Le Directeur de publication est M. LEDUC.
M. LEDUC Stéphane

2024-08-26 10:17 UTC, tpointel commented on src/content/page/mentions-legales.mdx
> +Le présent site est hébergé par Vercel Inc. dont le siège social est établi 440 N Barranca Ave #4133 Covina, CA 91723, USA et joignable par téléphone au numéro suivant : 5592887060.
Github ?

2024-08-26 12:30 UTC, MarcoPOtard commented on src/content/page/index.mdx
> +      **planet.fr - e-sante.fr - medisite**
modifié

2024-08-26 12:34 UTC, MarcoPOtard commented on src/content/page/index.mdx
> +      thumbnail: /src/assets/clients-matou-2.jpg
Modifié

2024-08-26 12:35 UTC, MarcoPOtard commented on src/content/page/index.mdx
> +      <span style="color: #F28705">GOOGLEWORKSPACE / GOOGLECLOUD / MICROSOFT AWS / STRIPE DIDOMI XIVO / FREEPRO DELL APPLE
Corrigé

2024-08-26 12:35 UTC, MarcoPOtard commented on src/content/page/mentions-legales.mdx
> +Le Directeur de publication est M. LEDUC.
Modifié

2024-08-29 12:17 UTC, tpointel approved these changes

2024-08-29 13:09 UTC, merged